# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae2dadd4d4d5f3180c45cdb715e83f133b98d2ffa6c7d3a1a5b7f0560b448711883cb0bc844329eb0266fdfee2421a913ef15bf3106196afd8c8a93cbf93937

test:
  secret_key_base: ade3455f5ccf70fe14c78c87e703e50b645b3d202821b8a6c34bf0c2161d0fd209feaaa4e0f0c290675396be94eaf39637b3b9b42da66d7044297b0744b43c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
